spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

springdoc:
  api-docs:
    path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      operation-sorter: method
      tags-sorter: alpha
      display-request-duration: true

jwt:
  secret: 09c2958b641c396bcdca4b30f0dd92e6d23e9b353adadf984f6d485575e703cd
  access-token-validity: 1800000
  refresh-token-validity: 1209600000


